NS_1_IP: ENC[AES256_GCM,data:xJl4rNiU3vg4i4NH+Q==,iv:61l6j+44CvIDFnJIdB2mPlTPBGwZGOVt+qd0EwuRw4I=,tag:GOchH+klfO2iBSn78Ji0ww==,type:str]
NS_2_IP: ENC[AES256_GCM,data:uOk8W0LuCY7hWSkZVw==,iv:g7XV12i1hkunwc0bHL6urSJ+KK6tqJsDjKDIBWkT5us=,tag:OP7+SjtK42a+qYTgEQMGsg==,type:str]
DNS_KEY_SECRET: ENC[AES256_GCM,data:ytmdLm0V+E9oLwGOlMPHvyhONXS8TNuf7Puxi9TJ16TGRmZWQxX7k9O/Cvk=,iv:F3eGr0jxEQEylxkcBdEtlBJLjJmmy3ZasQrF6VPtJGA=,tag:m81aSXeRrDeq58loB4/hrw==,type:str]
DAGGER_CLOUD_TOKEN: ENC[AES256_GCM,data:2JNei/UAgxsuQMC83DHiLEHR8hQxkKH4Q4RKCaUmfWbuifaTvhs6fdw5CGeufcPMJE0vwSk=,iv:LtEtIL4h2aEHvzuEr8CpN8Ne6w5HjfasGsXbYzB0G80=,tag:wm/D2S1hDCszklC/MiUaNg==,type:str]
VAULT_ROLE_ID: ENC[AES256_GCM,data:WJs/H2GoE6FQZINGkMtQmXpwC0LZe5ZfHPJaeYf34T5ApW19,iv:Cy4qyBNzyTHhIzenl0fiMtry7v3crXQgg9z93lDH9t0=,tag:odnvu6yiknibSsFuz/CDkA==,type:str]
VAULT_SECRET_ID: ENC[AES256_GCM,data:IUEnywEfn5+LoOYCEgTYM/pKdsg87GjM66Oxhvew/c2IM3XO,iv:Oi5lp26JM8kUkpOkN4InT6HN8na9mCXSqd0P3iQNEr8=,tag:AxUC58NetfPYIj23lEIgBw==,type:str]
sops:
    age:
        - recipient: age1595c6n7r3zu0aql8qeehlulds6g4cvavmphsyauk9uddks5hpuzqcg7c4u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdGs3dnNRRGoxZ3NCZWxj
            cDIyV3BNZnRCSVBYQVZyKytmRTY0aXRXNFNFCkpVVWtjTXF1YW51Y2U2L0NIcnNw
            NldyWFBadFBhR2JZY2hJa3UxQlY3ZEUKLS0tIEZTa3REMEE1NFFQNHE2RXZRRmpU
            Q1FIempZanpZNlRkRHJaL2h3bXp2T0UKlkxqr7LfA0+aaqyx1RABVdQq4E+Jc/df
            uG1tJOs5A8VPTO+4/fy0U0U7worgZaCEIliBld0ecO2MYnfK78/NnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T07:49:24Z"
    mac: ENC[AES256_GCM,data:VuJIn7ZnIoVGZkgG+We9hylFjXCYOROBbrJbp/uAKm5SD6rSvQIHC6CGlwzs6JDIF8QAKt3Kkyy8IyVd8P8Z/g6XOKfQ7EjZNqIlGubCZ6Km5YTZFVgRE8Rr3XAaP/wKmB+7xVkjrPSmPECHgg1Y4G42qxcz4NWOiimFvdW47Bk=,iv:whnvb+EplhGIy4d/SJG/H9x/o7fptcgNc1VYzOwN8iU=,tag:gkrtcaMoTiTla2iYfIfgXA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
