NS_1_IP: ENC[AES256_GCM,data:xJl4rNiU3vg4i4NH+Q==,iv:61l6j+44CvIDFnJIdB2mPlTPBGwZGOVt+qd0EwuRw4I=,tag:GOchH+klfO2iBSn78Ji0ww==,type:str]
NS_2_IP: ENC[AES256_GCM,data:uOk8W0LuCY7hWSkZVw==,iv:g7XV12i1hkunwc0bHL6urSJ+KK6tqJsDjKDIBWkT5us=,tag:OP7+SjtK42a+qYTgEQMGsg==,type:str]
DAGGER_CLOUD_TOKEN: ENC[AES256_GCM,data:2JNei/UAgxsuQMC83DHiLEHR8hQxkKH4Q4RKCaUmfWbuifaTvhs6fdw5CGeufcPMJE0vwSk=,iv:LtEtIL4h2aEHvzuEr8CpN8Ne6w5HjfasGsXbYzB0G80=,tag:wm/D2S1hDCszklC/MiUaNg==,type:str]
DOCKER_HUB_USER: ENC[AES256_GCM,data:4F0/vuOHvrCrjA==,iv:5JyNEThI39bJBvkGBeQ0CFT72MX4Is0Sh9etYklhvAs=,tag:K1UIO3CZsFspw5xAvNd3Fw==,type:str]
DOCKER_HUB_PASSWORD: ENC[AES256_GCM,data:lDmNB/M8A5vT6G7H,iv:nVNrFoLs2LTUmbOoBr7l41NYFWgmpfVgUDMM9oNcw4c=,tag:IHAZY/fEQ0CaPtOusCTPGQ==,type:str]
VAULT_ROLE_ID: ENC[AES256_GCM,data:uf7fePjjLuCCOISpnfdjh1AaSgXskowCqy8RKx64znVrMUEX,iv:Iq5F78d6H4GiZsRmBYmNlzSMBR13IRLPIlCZayHbX2g=,tag:QJ/vivHIuYJOL9tzULMlmQ==,type:str]
VAULT_SECRET_ID: ENC[AES256_GCM,data:bvupcLITo7r9BNSNvcBnUjwfQn0BEO7/0YrkgkBD93P+S6EI,iv:hF1z19F7vypsedtBTNZ0NAOIynTKPTPxK+6gXxcrmWE=,tag:oHPOf4HAb9g/h74Bj0Vkpg==,type:str]
sops:
    age:
        - recipient: age1595c6n7r3zu0aql8qeehlulds6g4cvavmphsyauk9uddks5hpuzqcg7c4u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdGs3dnNRRGoxZ3NCZWxj
            cDIyV3BNZnRCSVBYQVZyKytmRTY0aXRXNFNFCkpVVWtjTXF1YW51Y2U2L0NIcnNw
            NldyWFBadFBhR2JZY2hJa3UxQlY3ZEUKLS0tIEZTa3REMEE1NFFQNHE2RXZRRmpU
            Q1FIempZanpZNlRkRHJaL2h3bXp2T0UKlkxqr7LfA0+aaqyx1RABVdQq4E+Jc/df
            uG1tJOs5A8VPTO+4/fy0U0U7worgZaCEIliBld0ecO2MYnfK78/NnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-13T05:09:57Z"
    mac: ENC[AES256_GCM,data:Im4TLnrHGhAugGo27ogIBt3i+Vy6tHYWr1w9/QyNi3cS1ZJE8N/NJH7EGkPdkPxw0P8MZ0d3C0AT2VkGbw80ZiqY7PW++JEdPVzJ+HNf5pj7F6FU2OsLYhssClvIygcM2luFlOTyhAtlhlAk1Sdpp5UmGvILqg4NTwbNP213CDE=,iv:y49LQLi3WrfK0hRA/NqtP5V22l6vTH+lBzwDQ+xAPJw=,tag:Wj0or+oe6qjpsnRC01Jl8A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
