#!/usr/bin/env bash

#MISE description="Hook task that runs on directory entry."

echo "------------------------------------------"
figlet "$PROJECT_ID"
echo "Welcome to the $PROJECT_ID DEV Workspace!"
echo "------------------------------------------"

mise i -q

mise run vault:create-token
