#!/usr/bin/env bash

ssh -i ~/.ssh/admin_id_ecdsa -o StrictHostKeyChecking=no admin@vault.home.sflab.io 'sudo cat /etc/vault.d/vault-init-data.json'
ssh -i ~/.ssh/admin_id_ecdsa -o StrictHostKeyChecking=no admin@vault.home.sflab.io 'sudo cat /etc/vault.d/vault-secrets-approle.json'
